---
- name: Initial bootstrap
  hosts: localhost
  connection: local
  become: true

  vars:
    nfsmounts:
      - { src: "/storage", path: "/storage" }
      - { src: "/GDrive", path: "/GDrive" }

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
        
  pre_tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

  tasks:

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install packages
      package:
        name:
          - htop
          - vim-nox
          - inxi
          - neofetch
          - curl
          - keepassxc
          - wget
          - mlocate
          - nfs-common
          - gnome-tweak-tool
          - git
          - ufw
        state: present

    - name: Update locate db.
      shell: updatedb        
      changed_when: false
        
    - name: Add user Steve.
      user:
        name: steve
        password: $6$NIG2yNL5twSPoTMO$ke3lXegKbQsB1zaqAIJRctKi9XCxXBnxGnTDQDG8p2fJu6fZt0vgRlwylvVc1.BjlKjt3H9oGNubymSwLwouI1
        groups: wheel,sudo
        append: true
      ignore_errors: true

    - name: Copy steve's ssh key
      authorized_key:
        user: steve
        state: present
        key: "{{ lookup('file', 'files/id_ed25519.pub') }}"
      ignore_errors: true

    - name: Make new fstab entries for storage.
      mount:
        path: "{{ item.path }}"
        src: "192.168.137.20:/volume1{{ item.src }}"
        opts: defaults
        state: mounted
        fstype: nfs
      with_items: "{{ nfsmounts }}"

    - name: Copy dot files.
      copy:
        src: "files/{{ item }}"
        dest: "/home/steve/.{{ item }}"
        owner: steve
        group: steve
      with_items:
        - bashrc
        - bash_functions
        - bash_aliases
        - bash_logout
        - vimrc

    - name: Set up sudo for users.
      copy:
        src: "files/sudoer_{{ item }}"
        dest: "/etc/sudoers.d/{{ item }}"
        owner: root
        group: root
        mode: 0440
      with_items: 
        - steve

    - name: Add ansible-pull cron job
      cron:
        name: Ansible auto-provision
        user: root
        hour: '10'
        job: ansible-pull -o -U https://github.com/froststevefrost/ansible.git > /dev/null 2>&1

    - name: Update sshd configs
      copy:
        src: files/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644
      notify: restart sshd
