---
- name: Initial bootstrap
  hosts: localhost
  connection: local
  become: true

  vars:
    nfsmounts:
      - { src: "192.168.1.93:/volume1/storage", path: "/storage" }
      - { src: "192.168.1.93:/volume1/GDrive", path: "/GDrive" }

  tasks:

    - name: Install packages.
      package:
        name: 
          - htop
          - vim
          - vim-nox
          - python3-psutil
          - curl
          - wget 
          - mlocate
          - nfs-common
        state: present

    - name: Add user Steve.
      user:
        name: steve
        password: $6$NIG2yNL5twSPoTMO$ke3lXegKbQsB1zaqAIJRctKi9XCxXBnxGnTDQDG8p2fJu6fZt0vgRlwylvVc1.BjlKjt3H9oGNubymSwLwouI1

    - name: Make mount points.
      file:
        path: "{{ item.path }}"
        state: directory
        mode: 0770
      with_items: "{{ nfsmounts }}"

    - name: Make new fstab entries for storage.
      mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        opts: defaults
        state: mounted
        fstype: nfs
        dump: 0
        passno: 0
      with_items: "{{ nfsmounts }}"

    - name: Copy wallpaper file.
      block:
      - name: Copy wallpaper file
        copy:
          src: files/ansible-wallpaper.png
          dest: /usr/share/backgrounds/ansible-wallpaper.png
          owner: root
          group: root

      - name: Set wallpaper.
        become_user: steve
        dconf:
          key: "/org/gnome/desktop/background/picture-uri"
          value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

      - name: Set wallpaper position.
        become_user: steve
        dconf:
          key: "/org/gnome/desktop/background/picture-options"
          value: "'zoom'"
      when: ansible_lsb.id in 'Pop'

    - name: Copy bash files.
      copy:
        src: "files/{{ items }}"
        dest: "/home/steve/.{{ item }}"
        owner: steve
        group: steve
      with_items:
        -  bashrc
        -  bash_functions
        -  bash_aliases

    - name: Add new ansible user.
      user:
        name: velociraptor
        system: yes

    - name: Set up sudo for users.
      copy:
        src: "files/sudoer_{{ item }}"
        dest: "/etc/sudoers.d/{{ item }}"
        owner: root
        group: root
        mode: 0440
      with_items: 
        - velociraptor
        - steve

    - name: Add ansible-pull cron job
      cron:
        name: Ansible auto-provision
        user: velociraptor
        minute: "*/10"
        job: ansible-pull -o -U https://github.com/froststevefrost/ansible.git
