---
- name: Initial bootstrap
  hosts: localhost
  connection: local
  become: true

  vars:
    nfsmounts:
      - { src: "192.168.1.93:/volume1/storage", path: "/storage" }
      - { src: "192.168.1.93:/volume1/GDrive", path: "/GDrive" }

  tasks:

    - name: Install Signal's apt key.
      apt_key:
        keyserver:
          url: https://updates.signal.org/desktop/apt/keys.asc
          state: present

    - name: Add Signal's apt source.
      apt_repository:
        repo: deb https://updates.signal.org/desktop/apt xenial main
        state: present

    - name: Install packages.
      package:
        name: 
          - htop
          - tmux
          - vim-nox
          - neovim
          - python3-psutil
          - curl
          - wget 
          - mlocate
          - brave-browser
          - nfs-common
          - keepassxc
          - steam
          - signal-desktop
        state: present

        #    - name: Make new fstab entries for storage.
        #      mount:
        #        path: "{{ item.path }}"
        #        src: "{{ item.src }}"
        #        opts: defaults
        #        state: mounted
        #        fstype: nfs
        #        dump: 0
        #        pass: 0
        #      with_items: "{{ nfsmounts }}"

    - name: Copy wallpaper file.
      copy:
        src: files/ansible-wallpaper.png
        dest: /usr/share/backgrounds/ansible-wallpaper.png
        owner: root
        group: root

    - name: Set wallpaper.
      become_user: steve
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

    - name: Set wallpaper position.
      become_user: steve
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"

    - name: Copy .bashrc file.
      copy:
        src: files/bashrc
        dest: /home/steve/.bashrc
        owner: steve
        group: steve

    - name: Add new ansible user.
      user:
        name: velociraptor
        system: yes

    - name: Set up sudo for ansible user.
      copy:
        src: files/sudoer_velociraptor
        dest: /etc/sudoers.d/velociraptor
        owner: root
        group: root
        mode: 0440

    - name: Add ansible-pull cron job
      cron:
        name: Ansible auto-provision
        user: velociraptor
        minute: "*/10"
        job: ansible-pull -o -U https://github.com/froststevefrost/ansible.git
