---
- name: Initial bootstrap
  hosts: localhost
  connection: local
  become: true

  vars:
    nfspath: 192.168.137.20:/volume1
    nfsmounts:
      - { src: "/storage", path: "/storage" }
      - { src: "/GDrive", path: "/GDrive" }

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted

    - name: restart chrony
      service:
        name: chronyd
        state: restarted

    - name: restart firewalld
      service:
        name: firewalld
        state: restarted

    - name: restart ufw
      ufw:
        state: reloaded

  pre_tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

  tasks:

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install base packages
      package:
        name:
          - htop
          - vim-nox
          - inxi
          - neofetch
          - curl
          - keepassxc
          - wget
          - mlocate
          - git
          - chrony
        state: present
      when: ansible_os_family == "Debian"

    - name: Install ubuntu packages
      package:
        name:
          - ufw
          - gnome-tweak-tool
          - nfs-common
      when: ansible_os_family == "Debian"

    - name: Install RPM packages
      package:
        name:
          - firewalld
          - nfs-utils
      when: ansible_os_family == "RedHat"

    - name: Update locate db.
      shell: updatedb
      changed_when: false

    - name: Copy steve's ssh key
      authorized_key:
        user: steve
        state: present
        key: "{{ lookup('file', 'files/id_ed25519.pub') }}"
      ignore_errors: true

    - name: Make new fstab entries for storage.
      mount:
        path: "{{ item.path }}"
        src: "{{ nfspath }}{{ item.src }}"
        opts: defaults
        state: mounted
        fstype: nfs
      with_items: "{{ nfsmounts }}"

    - name: Copy dot files.
      copy:
        src: "files/{{ item }}"
        dest: "/home/steve/.{{ item }}"
        owner: steve
        group: steve
      with_items:
        - bashrc
        - bash_functions
        - bash_aliases
        - bash_logout
        - vimrc

    - name: Set timezone
      timezone:
        name: America/Anchorage
      notify: restart chrony

    - name: Set up sudo for users.
      copy:
        src: "files/sudoer_{{ item }}"
        dest: "/etc/sudoers.d/{{ item }}"
        owner: root
        group: root
        mode: 0440
      with_items:
        - steve

    - name: Add ansible-pull cron job
      cron:
        name: Ansible auto-provision
        user: root
        hour: '10'
        job: ansible-pull -o -U https://github.com/froststevefrost/ansible.git > /dev/null 2>&1

    - name: Update sshd configs
      copy:
        src: files/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644
      notify: restart sshd