---
- name: Initial bootstrap
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
      when: ansible_facts['distribution'] == "Debian"

  roles:
    - stfrost.bootstrap