# Make `ls' colorized
 LS_OPTIONS='--color=auto --group-directories-first'
 alias ll='ls $LS_OPTIONS -lAh'
 alias l='ls $LS_OPTIONS -l'
 alias l.='ls $LS_OPTIONS -ldh $(pwd)'
 alias ls='ls $LS_OPTIONS' 

 alias vi="vim"

# Some more alias to avoid making mistakes:
 alias rm='rm -i'
 alias cp='cp -i'
 alias mv='mv -i'

# grep colors
 alias grep='grep --color=always'
 alias egrep='egrep --color=always'
 alias fgrep='fgrep --color=always'

# QoL aliases 
 alias lsblk='lsblk -e 7'
 alias pip='pip3'
 alias python='python3'
 
 alias update='sudo apt update && sudo apt upgrade'
 alias editbash='vim ~/.bashrc && . ~/.bashrc'
 alias editalias='vim ~/.bash_aliases && . ~/.bash_aliases'
 alias editfunctions='vim ~/.bash_functions && . ~/.bash_functions'
 alias vg="vimgolf put $1"
