au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | exe "normal! zz" | endif
syntax enable
hi Comment cterm=italic gui=italic ctermfg=darkgray
set nocompatible
set autoindent
set smartindent
set shiftwidth=2
set tabstop=4
set expandtab
set hidden
set relativenumber
set number
set undofile
set spell
set title
set ignorecase
set smartcase
set incsearch
set showcmd
set backspace=indent,eol,start
set laststatus=2
set shortmess+=I
set wildmode=longest:full,full
set nowrap
set mouse=a
set scrolloff=8
set sidescrolloff=8
set nojoinspaces
set splitright
set confirm
set exrc
set backup
set backupdir=~/.local/share/vim/backup//
set updatetime=300
set redrawtime=10000
set list
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·
